gsb_appli_frais_gsb_forfaitligne:
    resource: "@GsbAppliFraisBundle/Resources/config/routing/forfaitligne.yml"
    prefix:   /gsb_forfaitligne

gsb_todo_list:
    path:     /todo
    defaults: { _controller: GsbAppliFraisBundle:Default:todo }


gsb_appli_frais_gsb_forfait:
    resource: "@GsbAppliFraisBundle/Resources/config/routing/forfait.yml"
    prefix:   /gsb_forfait

gsb_appli_frais_gsb_horsforfaitligne:
    resource: "@GsbAppliFraisBundle/Resources/config/routing/horsforfaitligne.yml"
    prefix:   /gsb_horsforfaitligne

gsb_appli_frais_gsb_statut:
    resource: "@GsbAppliFraisBundle/Resources/config/routing/statut.yml"
    prefix:   /gsb_statut

gsb_appli_frais_gsb_fiche:
    resource: "@GsbAppliFraisBundle/Resources/config/routing/fiche.yml"
    prefix:   /gsb_fiche

gsb_appli_frais_gsb_etat:
    resource: "@GsbAppliFraisBundle/Resources/config/routing/etat.yml"
    prefix:   /gsb_etat

gsb_appli_frais_gsb_employe:
    resource: "@GsbAppliFraisBundle/Resources/config/routing/employe.yml"
    prefix:   /gsb_employe

gsb_appli_frais_visiteur:
    resource: "@GsbAppliFraisBundle/Resources/config/routing/visiteur.yml"
    prefix:    /visiteur

gsb_appli_frais_historique:
    resource: "@GsbAppliFraisBundle/Resources/config/routing/historique.yml"
    prefix:    /visiteur/historique

gsb_appli_frais_comptable:
    resource: "@GsbAppliFraisBundle/Resources/config/routing/comptable.yml"
    prefix:    /comptable

gsb_appli_frais_admin:
    resource: "@GsbAppliFraisBundle/Resources/config/routing/admin.yml"
    prefix:   /admin



login:
    pattern:   /portal
    defaults:  { _controller: GsbAppliFraisBundle:Login:login }
login_check:
    pattern:   /portal_check

logout:
    pattern:   /logout

connexion:
    pattern:   /connexion
    defaults:  { _controller: GsbAppliFraisBundle:Login:redirect }

pdf:
    pattern:   /pdf/{idFiche}
    defaults:  { _controller: GsbAppliFraisBundle:Pdf:index }

