gsb_appli_frais_visiteur:
    resource: "@GsbAppliFraisBundle/Resources/config/routing/visiteur.yml"
    prefix:    /visiteur

gsb_appli_frais_historique:
    resource: "@GsbAppliFraisBundle/Resources/config/routing/historique.yml"
    prefix:    /visiteur/historique

gsb_appli_frais_comptable:
    resource: "@GsbAppliFraisBundle/Resources/config/routing/comptable.yml"
    prefix:    /comptable


gsb_appli_frais_admin:
    resource: "@GsbAppliFraisBundle/Resources/config/routing/admin.yml"
    prefix:   /admin

login:
    pattern:   /portal
    defaults:  { _controller: GsbAppliFraisBundle:Login:login }
login_check:
    pattern:   /portal_check

logout:
    pattern:   /logout

connexion:
    pattern:   /connexion
    defaults:  { _controller: GsbAppliFraisBundle:Login:redirect }

gsb_appli_frais_jury:
    path:     /jury
    defaults: { _controller: "GsbAppliFraisBundle:Jury:index" }