comptable:
    path:     /
    defaults: { _controller: "GsbAppliFraisBundle:Comptable:index" }

comptable_show:
    path:     /show/{idFiche}
    defaults: { _controller: "GsbAppliFraisBundle:Comptable:show" }

comptable_find_visit:
    path:     /find
    defaults: { _controller: "GsbAppliFraisBundle:Comptable:find" }
    methods:  POST