comptable:
    path:     /
    defaults: { _controller: "GsbAppliFraisBundle:Comptable:index" }

comptable_show:
    path:     /loadshow/{idFiche}
    defaults: { _controller: "GsbAppliFraisBundle:Comptable:loadshow" }

comptable_show_fiche:
    path:     /show
    defaults: { _controller: "GsbAppliFraisBundle:Comptable:show" }

comptable_find_visit:
    path:     /find/visiteur
    defaults: { _controller: "GsbAppliFraisBundle:Comptable:findVisiteur" }
    methods:  POST

comptable_find:
    path:     /find
    defaults: { _controller: "GsbAppliFraisBundle:Comptable:find" }
    methods:  POST

comptable_maj:
    path:     /maj
    defaults: { _controller: "GsbAppliFraisBundle:Comptable:miseAJour" }