gsb_etat:
    path:     /
    defaults: { _controller: "GsbAppliFraisBundle:Etat:index" }

gsb_etat_show:
    path:     /{id}/show
    defaults: { _controller: "GsbAppliFraisBundle:Etat:show" }

gsb_etat_new:
    path:     /new
    defaults: { _controller: "GsbAppliFraisBundle:Etat:new" }

gsb_etat_create:
    path:     /create
    defaults: { _controller: "GsbAppliFraisBundle:Etat:create" }
    methods:  POST

gsb_etat_edit:
    path:     /{id}/edit
    defaults: { _controller: "GsbAppliFraisBundle:Etat:edit" }

gsb_etat_update:
    path:     /{id}/update
    defaults: { _controller: "GsbAppliFraisBundle:Etat:update" }
    methods:  [POST, PUT]

gsb_etat_delete:
    path:     /{id}/delete
    defaults: { _controller: "GsbAppliFraisBundle:Etat:delete" }
    methods:  [POST, DELETE]
