gsb_fiche:
    path:     /
    defaults: { _controller: "GsbAppliFraisBundle:Fiche:index" }

gsb_fiche_show:
    path:     /{id}/show
    defaults: { _controller: "GsbAppliFraisBundle:Fiche:show" }

gsb_fiche_new:
    path:     /new
    defaults: { _controller: "GsbAppliFraisBundle:Fiche:new" }

gsb_fiche_create:
    path:     /create
    defaults: { _controller: "GsbAppliFraisBundle:Fiche:create" }
    methods:  POST

gsb_fiche_edit:
    path:     /{id}/edit
    defaults: { _controller: "GsbAppliFraisBundle:Fiche:edit" }

gsb_fiche_update:
    path:     /{id}/update
    defaults: { _controller: "GsbAppliFraisBundle:Fiche:update" }
    methods:  [POST, PUT]

gsb_fiche_delete:
    path:     /{id}/delete
    defaults: { _controller: "GsbAppliFraisBundle:Fiche:delete" }
    methods:  [POST, DELETE]
