gsb_forfait:
    path:     /
    defaults: { _controller: "GsbAppliFraisBundle:Forfait:index" }

gsb_forfait_show:
    path:     /{id}/show
    defaults: { _controller: "GsbAppliFraisBundle:Forfait:show" }

gsb_forfait_new:
    path:     /new
    defaults: { _controller: "GsbAppliFraisBundle:Forfait:new" }

gsb_forfait_create:
    path:     /create
    defaults: { _controller: "GsbAppliFraisBundle:Forfait:create" }
    methods:  POST

gsb_forfait_edit:
    path:     /{id}/edit
    defaults: { _controller: "GsbAppliFraisBundle:Forfait:edit" }

gsb_forfait_update:
    path:     /{id}/update
    defaults: { _controller: "GsbAppliFraisBundle:Forfait:update" }
    methods:  [POST, PUT]

gsb_forfait_delete:
    path:     /{id}/delete
    defaults: { _controller: "GsbAppliFraisBundle:Forfait:delete" }
    methods:  [POST, DELETE]
