historique:
    path:     /{id}
    defaults: { _controller: "GsbAppliFraisBundle:Historique:index" }


historique_find_dateEtat:
    path:     /search/{id}
    defaults: { _controller: "GsbAppliFraisBundle:Historique:findFiche" }
    methods:  [POST, PUT]

historique_find_dateStatut:
    path:     /find/{id}
    defaults: { _controller: "GsbAppliFraisBundle:Historique:findLigne" }
    methods:  [POST, PUT]