historique:
    path:     /{id}
    defaults: { _controller: "GsbAppliFraisBundle:Historique:index" }


historique_test:
    path:     /date/{id}
    defaults: { _controller: "GsbAppliFraisBundle:Historique:findDate" }
    methods:  [POST, PUT]