historique:
    path:     /
    defaults: { _controller: "GsbAppliFraisBundle:Historique:index" }


historique_find_dateEtat:
    path:     /search/
    defaults: { _controller: "GsbAppliFraisBundle:Historique:findFiche" }
    methods:  [POST, PUT]

historique_find_dateStatut:
    path:     /find/
    defaults: { _controller: "GsbAppliFraisBundle:Historique:findLigne" }
    methods:  [POST, PUT]

historique_show:
    path:     /show/{idFiche}
    defaults: { _controller: "GsbAppliFraisBundle:Historique:show" }