gsb_horsforfaitligne:
    path:     /
    defaults: { _controller: "GsbAppliFraisBundle:HorsForfaitLigne:index" }

gsb_horsforfaitligne_show:
    path:     /{id}/show
    defaults: { _controller: "GsbAppliFraisBundle:HorsForfaitLigne:show" }

gsb_horsforfaitligne_new:
    path:     /new
    defaults: { _controller: "GsbAppliFraisBundle:HorsForfaitLigne:new" }

gsb_horsforfaitligne_create:
    path:     /create
    defaults: { _controller: "GsbAppliFraisBundle:HorsForfaitLigne:create" }
    methods:  POST

gsb_horsforfaitligne_edit:
    path:     /{id}/edit
    defaults: { _controller: "GsbAppliFraisBundle:HorsForfaitLigne:edit" }

gsb_horsforfaitligne_update:
    path:     /{id}/update
    defaults: { _controller: "GsbAppliFraisBundle:HorsForfaitLigne:update" }
    methods:  [POST, PUT]

gsb_horsforfaitligne_delete:
    path:     /{id}/delete
    defaults: { _controller: "GsbAppliFraisBundle:HorsForfaitLigne:delete" }
    methods:  [POST, DELETE]
