gsb_statut:
    path:     /
    defaults: { _controller: "GsbAppliFraisBundle:Statut:index" }

gsb_statut_show:
    path:     /{id}/show
    defaults: { _controller: "GsbAppliFraisBundle:Statut:show" }

gsb_statut_new:
    path:     /new
    defaults: { _controller: "GsbAppliFraisBundle:Statut:new" }

gsb_statut_create:
    path:     /create
    defaults: { _controller: "GsbAppliFraisBundle:Statut:create" }
    methods:  POST

gsb_statut_edit:
    path:     /{id}/edit
    defaults: { _controller: "GsbAppliFraisBundle:Statut:edit" }

gsb_statut_update:
    path:     /{id}/update
    defaults: { _controller: "GsbAppliFraisBundle:Statut:update" }
    methods:  [POST, PUT]

gsb_statut_delete:
    path:     /{id}/delete
    defaults: { _controller: "GsbAppliFraisBundle:Statut:delete" }
    methods:  [POST, DELETE]
