visiteur:
    path:     /{id}
    defaults: { _controller: "GsbAppliFraisBundle:Visiteur:saisie" }

visiteur_update_forfait_ligne:
    path:     /{idLigne}/{idVisit}/update
    defaults: { _controller: "GsbAppliFraisBundle:Visiteur:updateForfaitLigne" }
    methods:  [POST, PUT]

visiteur_create_hors_forfait_ligne:
    path:     /{idVisit}/create
    defaults: { _controller: "GsbAppliFraisBundle:Visiteur:createHorsForfaitLigne" }
    methods:  POST

visiteur_historique:
    path:     /{id}/historique
    defaults: { _controller: "GsbAppliFraisBundle:Visiteur:historique" }

visiteur_ligneHorsForfait_edit:
    path:     /{idVisit}/{idLigne}/edit
    defaults: { _controller: "GsbAppliFraisBundle:Visiteur:editLigne" }

visiteur_ligneHorsForfait_delete:
    path:     /{idVisit}/{id}/delete
    defaults: { _controller: "GsbAppliFraisBundle:Visiteur:deleteLigne" }
    methods:  [POST, DELETE]

visiteur_ligneHorsForfait_update:
    path:     /{idVisit}/{id}/updateHf
    defaults: { _controller: "GsbAppliFraisBundle:Visiteur:updateLigne" }
    methods:  [POST, PUT]