security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /portal
                check_path:  /portal_check
                default_target_path: /connexion
                always_use_default_target_path: true

            logout:
                path:   /logout
                target: /portal

    access_control:
        - { path: ^/visiteur, roles: ROLE_VISITEUR }

    providers:
        main:
            entity: { class: Gsb\AppliFraisBundle\Entity\Employe, property: login }

    encoders:
        Gsb\AppliFraisBundle\Entity\Employe: plaintext
