security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /portal
                check_path:  /portal_check

            logout:
                path:   /logout
                target: /portal

    access_control:
        - { path: ^/visiteur, roles: ROLE_ADMIN }

    providers:
        in_memory:
             memory:
                users:
                    ryan:  { password: ryanpass, roles: 'ROLE_USER' }
                    admin: { password: kitten, roles: 'ROLE_ADMIN' }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
