<?php

namespace Gsb\AppliFraisBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FicheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheRepository extends EntityRepository
{
	public function ficheByDate(QueryBuilder $qb, $dateDeb, $dateFin)
  {
    $qb
      ->Where('f.date BETWEEN :start AND :end')
      ->setParameter('start', $dateDeb)
      ->setParameter('end',   $dateFin)
    ;
  }
}
