<?php

namespace Gsb\AppliFraisBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ForfaitLigneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForfaitLigneRepository extends EntityRepository
{
}
