<?php

namespace Proxies\__CG__\Gsb\AppliFraisBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Fiche extends \Gsb\AppliFraisBundle\Entity\Fiche implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'date', 'nbJustificatifs', 'dateModification', 'montantValide', 'employe', 'etat', 'horsForfaitLignes', 'forfaitLignes');
        }

        return array('__isInitialized__', 'id', 'date', 'nbJustificatifs', 'dateModification', 'montantValide', 'employe', 'etat', 'horsForfaitLignes', 'forfaitLignes');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Fiche $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', array($date));

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', array());

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbJustificatifs($nbJustificatifs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbJustificatifs', array($nbJustificatifs));

        return parent::setNbJustificatifs($nbJustificatifs);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbJustificatifs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbJustificatifs', array());

        return parent::getNbJustificatifs();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateModification($dateModification)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateModification', array($dateModification));

        return parent::setDateModification($dateModification);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateModification()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateModification', array());

        return parent::getDateModification();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontantValide($montantValide)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontantValide', array($montantValide));

        return parent::setMontantValide($montantValide);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantValide()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantValide', array());

        return parent::getMontantValide();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmploye(\Gsb\AppliFraisBundle\Entity\Employe $employe = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmploye', array($employe));

        return parent::setEmploye($employe);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmploye()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmploye', array());

        return parent::getEmploye();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat(\Gsb\AppliFraisBundle\Entity\Etat $etat = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', array($etat));

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', array());

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function addHorsForfaitLigne(\Gsb\AppliFraisBundle\Entity\HorsForfaitLigne $horsForfaitLignes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addHorsForfaitLigne', array($horsForfaitLignes));

        return parent::addHorsForfaitLigne($horsForfaitLignes);
    }

    /**
     * {@inheritDoc}
     */
    public function removeHorsForfaitLigne(\Gsb\AppliFraisBundle\Entity\HorsForfaitLigne $horsForfaitLignes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeHorsForfaitLigne', array($horsForfaitLignes));

        return parent::removeHorsForfaitLigne($horsForfaitLignes);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorsForfaitLignes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorsForfaitLignes', array());

        return parent::getHorsForfaitLignes();
    }

    /**
     * {@inheritDoc}
     */
    public function addForfaitLigne(\Gsb\AppliFraisBundle\Entity\ForfaitLigne $forfaitLignes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addForfaitLigne', array($forfaitLignes));

        return parent::addForfaitLigne($forfaitLignes);
    }

    /**
     * {@inheritDoc}
     */
    public function removeForfaitLigne(\Gsb\AppliFraisBundle\Entity\ForfaitLigne $forfaitLignes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeForfaitLigne', array($forfaitLignes));

        return parent::removeForfaitLigne($forfaitLignes);
    }

    /**
     * {@inheritDoc}
     */
    public function getForfaitLignes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getForfaitLignes', array());

        return parent::getForfaitLignes();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
